import * as fs from 'fs';
import * as path from 'path';
import { settings } from './config.js';

export class ScaffoldSecurityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ScaffoldSecurityError';
  }
}

export class ProjectScaffolder {
  /**
   * Validates target path against root path to prevent path traversal attacks.
   */
  public static validatePath(targetPath: string, rootPath: string = settings.WORKSPACE_ROOT): string {
    const resolvedTarget = path.resolve(targetPath);
    const resolvedRoot = path.resolve(rootPath);

    // Verify that the target is a subdirectory of the allowed root
    if (!resolvedTarget.startsWith(resolvedRoot)) {
      throw new ScaffoldSecurityError(
        `Security Violation: Target path '${resolvedTarget}' is outside the allowed workspace root '${resolvedRoot}'.`
      );
    }
    return resolvedTarget;
  }

  public scaffold(synthesisOutput: any, projectDirectory: string): any {
    const writtenFiles: string[] = [];
    let validatedDir = '';
    try {
      validatedDir = ProjectScaffolder.validatePath(projectDirectory);
    } catch (err: any) {
      console.error(`Path validation security failure: ${err.message}`);
      return { status: 'error', message: err.message };
    }

    console.warn(`Scaffolding project inside validated directory: ${validatedDir}`);
    fs.mkdirSync(validatedDir, { recursive: true });

    const payload = synthesisOutput?.synthesis_payload || {};
    const pName = payload.paradigm_name || 'Cross-Domain Hybrid Prototype';
    const bridge = payload.structural_bridge || 'No bridge data available.';
    const mechanics = payload.hybrid_mechanics || 'No operational mechanics specified.';
    const mathFormula = payload.mathematical_grafting_formula || 'S_c = f(A, B)';
    const tradeoffs = payload.critical_tradeoffs || [];

    const tradeoffsMd = tradeoffs.map((t: string) => `* **Risk:** ${t}`).join('\n');

    try {
      // 1. Write README.md
      const readmePath = path.join(validatedDir, 'README.md');
      fs.writeFileSync(
        readmePath,
        `# ${pName.toUpperCase()}

## Conceptual Bridge
${bridge}

## Operational Mechanics
${mechanics}

## Mathematical Foundation
$$\\${mathFormula}$$

## System Risks
${tradeoffsMd}

---
*Generated by Ideation GOAT Scaffolder.*
`,
        'utf8'
      );
      writtenFiles.push('README.md');

      // 2. Write math_engine.py
      const enginePath = path.join(validatedDir, 'math_engine.py');
      fs.writeFileSync(
        enginePath,
        `"""
Mathematical Engine for ${pName}
Formula: ${mathFormula}
"""
import math
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("MathEngine")

def calculate_graft_metrics(v_a: list, v_b: list, delta_t: float, gamma: float = 0.95) -> float:
    """
    Computes convergence/decay across distinct domain spaces.
    LaTeX Formula: ${mathFormula}
    """
    logger.info("Initializing convergence calculations.")
    try:
        dot_product = sum(a * b for a, b in zip(v_a, v_b))
        decay_factor = math.pow(gamma, delta_t)
        score = dot_product * decay_factor
        return score
    except Exception as e:
        logger.error(f"Error during calculation loop: {e}")
        return 0.0
`,
        'utf8'
      );
      writtenFiles.push('math_engine.py');

      // 3. Write state_buffer.py
      const bufferPath = path.join(validatedDir, 'state_buffer.py');
      fs.writeFileSync(
        bufferPath,
        `"""
State Buffer & Eviction Registry for ${pName}
"""
import time
from typing import Dict, Any, Optional

class StateBuffer:
    """
    Non-blocking state storage structure utilizing dynamic eviction rules.
    """
    def __init__(self):
        self.registry: Dict[str, Any] = {}
        self.write_rates: Dict[str, float] = {}
        
    def register_state(self, key: str, payload: Any):
        """
        Saves key payload and increments local traffic density coordinates.
        """
        self.registry[key] = payload
        self.write_rates[key] = self.write_rates.get(key, 0.0) + 1.0
        
    def check_eviction(self) -> Optional[str]:
        """
        Determines eviction candidate based on dynamic thresholds.
        """
        if not self.registry:
            return None
        candidate = min(self.write_rates, key=self.write_rates.get)
        return candidate
`,
        'utf8'
      );
      writtenFiles.push('state_buffer.py');

      // 4. Write requirements.txt
      const reqPath = path.join(validatedDir, 'requirements.txt');
      fs.writeFileSync(reqPath, 'pydantic>=2.0.0\n', 'utf8');
      writtenFiles.push('requirements.txt');

      // 5. Generate Docker scaffolding
      let framework = 'python';
      const pNameLower = pName.toLowerCase();
      if (['express', 'node', 'nest', 'next', 'react', 'vue'].some((k) => pNameLower.includes(k))) {
        framework = 'node';
      } else if (['axum', 'actix', 'rust'].some((k) => pNameLower.includes(k))) {
        framework = 'rust';
      } else if (['gin', 'fiber', 'go'].some((k) => pNameLower.includes(k))) {
        framework = 'go';
      }

      const dockerFiles = this.generateDockerFiles(validatedDir, framework);
      writtenFiles.push(...dockerFiles);

      return {
        status: 'success',
        scaffold_directory: validatedDir,
        files_created: [
          'README.md',
          'math_engine.py',
          'state_buffer.py',
          'requirements.txt',
          'Dockerfile',
          'docker-compose.yml',
          '.env.example'
        ],
        instruction: 'Open the directory in your workspace and run docker-compose up to start your environment.'
      };
    } catch (err: any) {
      console.error(`Scaffolding operation failed midway: ${err.message}`);
      // Rollback: Clean up partially written files
      for (const fName of writtenFiles) {
        try {
          fs.unlinkSync(path.join(validatedDir, fName));
        } catch {
          // ignore
        }
      }
      return { status: 'error', message: `Scaffolding failed: ${err.message}` };
    }
  }

  public generateDockerFiles(validatedDir: string, targetFramework: string): string[] {
    const framework = targetFramework.toLowerCase().trim();
    let dockerfileContent = '';

    if (framework === 'node') {
      dockerfileContent = `# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build --if-present

# Production Stage
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["npm", "start"]
`;
    } else if (framework === 'rust') {
      dockerfileContent = `# Build Stage
FROM rust:1.75-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src/ ./src/
RUN cargo build --release

# Production Stage
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/app-binary ./app-binary
EXPOSE 8080
CMD ["./app-binary"]
`;
    } else if (framework === 'go') {
      dockerfileContent = `# Build Stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app-binary .

# Production Stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/app-binary .
EXPOSE 8080
CMD ["./app-binary"]
`;
    } else {
      // Default to Python
      dockerfileContent = `# Build Stage
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Production Stage
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /root/.local /root/.local
COPY . .
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["python", "math_engine.py"]
`;
    }

    const composeContent = `version: '3.8'

services:
  app:
    build: .
    ports:
      - "\${PORT:-8080}:8080"
    environment:
      - NODE_ENV=\${NODE_ENV:-development}
      - DATABASE_URL=\${DATABASE_URL}
      - API_KEY=\${API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
`;

    const envContent = `# App Configuration
PORT=8080
NODE_ENV=development

# Database configuration
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/db_name

# Security Auth settings
API_KEY=your_sandbox_api_key_goes_here
`;

    fs.writeFileSync(path.join(validatedDir, 'Dockerfile'), dockerfileContent, 'utf8');
    fs.writeFileSync(path.join(validatedDir, 'docker-compose.yml'), composeContent, 'utf8');
    fs.writeFileSync(path.join(validatedDir, '.env.example'), envContent, 'utf8');

    return ['Dockerfile', 'docker-compose.yml', '.env.example'];
  }
}
